#!/bin/bash
cd `dirname $0`

if test -e /proc/
then {
    export CPUCOUNT=`grep -c ^processor /proc/cpuinfo`
    export TOOLSET=gcc
    export LD_LIBRARY_PATH=../dist/lib
    EXTENSION="so"
}
else {
    export CPUCOUNT=`sysctl -n hw.ncpu`
    export TOOLSET=darwin
    export DYLD_LIBRARY_PATH=../dist/lib
    EXTENSION="dylib"
    export LANG=C
}
fi

if ../bjam toolset=$TOOLSET  -j$CPUCOUNT `../python.opts.sh` $*
then {
    echo fost-py $* OK
    exit 0
} else {
    exit 1
}
fi

