#!/bin/bash
cd `dirname $0`

if ./build
then {
    mkdir ../dist/include
    cp -R ../Boost/boost/include/boost-1_39/boost ../dist/include/boost
    svn export ../fost-base/Cpp/include/fost ../dist/include/fost
    svn export ../fost-internet/Cpp/include/fost ../dist/include/fost --force
    svn export ../fost-orm/Cpp/include/fost ../dist/include/fost --force
    svn export Cpp/include/fost ../dist/include/fost --force
} else {
    exit 1
}
fi
