#!/bin/bash
export PYTHONPATH=`dirname $0`/../../Python/
export LD_LIBRARY_PATH=`dirname $0`/../../../dist/lib/
`dirname $0`/../../../dist/bin/fpython `dirname $0`/../../Python/Fost/Test/spider.py $*
