#!/bin/bash

if test -e ../../dist
then {
    rm -rf ../../dist
}
fi
cd ..
if bjam -j`grep ^processor /proc/cpuinfo | wc -l` --toolset=gcc --preserve-test-targets release
then {
    cd debian
    echo Starting package build
} else {
    cd debian
    exit 1
}
fi

export FOST_PY_VERSION=0.`svn log .. --limit 1 | grep -o 'r[0-9]*' | grep -o '[0-9]*'`
if test x86_64 = `uname -m`
then {
    export FOST_PY_ARCH=amd64
} else {
    export FOST_PY_ARCH=i386
}
fi
export FOST_PY_PACKAGE=fost-py_$FOST_PY_VERSION-1_$FOST_PY_ARCH

if test -e $FOST_PY_PACKAGE
then {
    rm -rf $FOST_PY_PACKAGE
}
fi

mkdir $FOST_PY_PACKAGE
mkdir $FOST_PY_PACKAGE/DEBIAN
cp -r ../../dist/ $FOST_PY_PACKAGE/usr
chmod -R a-x $FOST_PY_PACKAGE/usr/lib/*.so
chmod a-x $FOST_PY_PACKAGE/usr/lib/*.0
rm $FOST_PY_PACKAGE/usr/lib/_*.so
mkdir $FOST_PY_PACKAGE/usr/share
mkdir $FOST_PY_PACKAGE/usr/share/doc
mkdir $FOST_PY_PACKAGE/usr/share/doc/fost-py
echo Copyright 1995-2008 Felspar Co Ltd>$FOST_PY_PACKAGE/usr/share/doc/fost-py/copyright
cat ../LICENSE_1_0.txt >> $FOST_PY_PACKAGE/usr/share/doc/fost-py/copyright

echo Package: fost-py>$FOST_PY_PACKAGE/DEBIAN/control
echo Version: $FOST_PY_VERSION-1>>$FOST_PY_PACKAGE/DEBIAN/control
echo Section: python>>$FOST_PY_PACKAGE/DEBIAN/control
echo Priority: optional>>$FOST_PY_PACKAGE/DEBIAN/control
echo Architecture: $FOST_PY_ARCH>>$FOST_PY_PACKAGE/DEBIAN/control
echo Depends: libc6, python \(\>=2.5.2-0ubuntu1\), openssl \(\>=0.9.8g\) >>$FOST_PY_PACKAGE/DEBIAN/control
echo Maintainer: Kirit Saelensminde \<kirit@felspar.com\> >>$FOST_PY_PACKAGE/DEBIAN/control
cat description.txt >>$FOST_PY_PACKAGE/DEBIAN/control

#echo ldconfig>$FOST_PY_PACKAGE/DEBIAN/postinst
#chmod +x $FOST_PY_PACKAGE/DEBIAN/postinst

fakeroot dpkg-deb --build $FOST_PY_PACKAGE
lintian $FOST_PY_PACKAGE.deb
mv -f $FOST_PY_PACKAGE.deb ../../dist

rm -rf $FOST_PY_PACKAGE
