#!/bin/bash
cd `dirname $0`/../../..

FOST_PY_VERSION=4.09.09.`svn log ./fost-py --limit 1 | grep -o 'r[0-9]*' | grep -o '[0-9]*'`
FOST_PY_FOLDER=fost-py-$FOST_PY_VERSION

rm -rf dist
mkdir ./dist
mkdir ./dist/$FOST_PY_FOLDER

svn export ./Boost ./dist/$FOST_PY_FOLDER/Boost
svn export ./Boost/1_39_0 ./dist/$FOST_PY_FOLDER/Boost/1_39_0
svn export ./PostgreSQL ./dist/$FOST_PY_FOLDER/PostgreSQL
svn export ./fost-base ./dist/$FOST_PY_FOLDER/fost-base
svn export ./fost-internet ./dist/$FOST_PY_FOLDER/fost-internet
svn export ./fost-orm ./dist/$FOST_PY_FOLDER/fost-orm
svn export ./fost-postgres ./dist/$FOST_PY_FOLDER/fost-postgres
svn export ./fost-py ./dist/$FOST_PY_FOLDER/fost-py
cp ./fost-py/Installers/ppa/Makefile ./dist/$FOST_PY_FOLDER

cd ./dist
tar czf fost-py_$FOST_PY_VERSION.orig.tar.gz $FOST_PY_FOLDER
svn export ../fost-py/Installers/ppa/debian $FOST_PY_FOLDER/debian

cd $FOST_PY_FOLDER
debuild -S -kkirit@felspar.com
